# Generated by Django 5.0.6 on 2024-07-12 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_alter_task_options_rename_created_by_task_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='user',
            new_name='owner',
        ),
    ]
